### ISSUE TITLE
Using v3.0.0 unable to pass the prop 'attachment' to Tether Component 

### ISSUE THREAD

**Issue by aalanders** [danreeves/react-tether#232] opened 2023-06-22 21:23 UTC
I am using react-tether and if I use the latest version v3.0.0, the component does not accept the prop 'attachment'. The Type file does not include attachment, so it throws an error. 

![Screenshot 2023-06-22 at 2 10 07 PM](https://github.com/danreeves/react-tether/assets/29340714/2f4975ce-65fa-4c40-87ff-b0928d3c2d0b)

When I downgrade to v2.7.0, it works. (The attachment prop is accepted, there is no error)

Snippet of my code:
```
import TetherComponent from 'react-tether';

return  <TetherComponent
            attachment={attachment} //TypeScript says attachment does not exist as a prop
            constraints={constraints}
            renderElementTo={target}
            targetAttachment={TARGET_PLACEMENT_OPTIONS[targetPlacement]}
            renderTarget={(ref: React.Ref<any>) =>
                popoverTarget(ref, setIsOpen, isOpen)
            }
            renderElement={(ref: React.Ref<any>) => element?.(ref, isOpen)}
            renderElementTag={tagName}
        />
````

In my package.json in devDependencies I have included "@types/react-tether": "^1.0.0"

**Comment by mescalas** [comment] 2023-06-29 08:56
Same issue here

**Comment by ryprice** [comment] 2023-07-11 22:35
Same here. As a hacky **temporary** workaround, you can update `ReactTetherProps` in `node_modules/react-tether/lib/react-tether.d.ts` to use & instead of extends, but of course this will only last until you update the package.
`type ReactTetherProps = Tether.ITetherOptions & {`

@danreeves I believe this problem is already fixed by #229, specifically [here](https://github.com/danreeves/react-tether/commit/1d904c48c3e43e5b449094b430d5d5bad6ec3511#diff-9bb32b123654fed062a91bff3feb02bb7f090345ab428467d1fd71eb54f8f950R64-R65), but it doesn't seem to be in the current 3.0.1 version thru npm. Thanks!

**Comment by ryprice** [comment] 2023-07-26 20:20
@danreeves checking in on whether you can release an updated version to npm? Thanks.

**Comment by ryprice** [comment] 2023-10-10 18:32
@danreeves ping. Can you help here?

**Comment by danreeves** [comment] 2023-10-10 18:34
oh shit, lemme take a look at whats wrong

**Comment by danreeves** [comment] 2023-10-10 19:23
Just had a play around, it seems like the issue is that `@types/tether` isn't being installed. You can see it working correctly when it is here: https://codesandbox.io/s/react-typescript-forked-pc8jv6?file=/src/App.tsx

**Comment by danreeves** [comment] 2023-10-10 19:28
Version 3.0.3 includes `@types/tether` in its dependencies so this shouldn't be a problem going forward: https://codesandbox.io/s/react-typescript-forked-mfp6tf?file=/src/App.tsx

**Closed** 2024-02-03 17:15 UTC
