### ISSUE TITLE
module export is TetherComponent, not {default: TetherComponent}

### ISSUE THREAD

**Issue by ryprice** [danreeves/react-tether#52] opened 2017-09-06 02:33 UTC
It seems that, at least in my app, `import TetherComponent from 'react-tether';` doesn't work, (sets TetherComponent to undefined) while `import * as TetherComponet from 'react-tether';` works as expected (sets TetherComponent to the TetherComponent react class). 

What seems to be happening is that [react-tether.js](https://github.com/souporserious/react-tether/blob/master/src/react-tether.js#L1) compiles to something like this:

**Current behavior**
```javascript
export default from './TetherComponent';
```
```javascript
// compiles to this:
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = undefined;
var _TetherComponent = require('./TetherComponent');
var _TetherComponent2 = _interopRequireDefault(_TetherComponent);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
exports.default = _TetherComponent2.default;
module.exports = exports['default'];
```

**Expected behavior**
```javascript
// Proposed change:
export {default as TetherComponent} from './TetherComponent';
export default from './TetherComponent';
```
```javascript
// Compiles to this:
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = exports.TetherComponent = undefined;
var _TetherComponent = require('./TetherComponent');
Object.defineProperty(exports, 'TetherComponent', {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_TetherComponent).default;
  }
});
var _TetherComponent2 = _interopRequireDefault(_TetherComponent);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
exports.default = _TetherComponent2.default;
```

I'm not sure why, but as you can see, the current code directly exports TetherComponent instead of {default: TetherComponent} which makes it a bit obtuse to import correctly. I think it will be a breaking change though.

**Comment by danreeves** [comment] 2017-11-15 11:18
Are you able to supply a reproduction of this problem so that I can test it?

**Comment by ryprice** [comment] 2017-12-06 05:44
Unsurprisingly, I cannot repro it in your [example](https://github.com/danreeves/react-tether/tree/master/example), probably due to subtle difference in compilers. It would be substantially harder to create an environment similar to @voliva's and mine as we're using typescript. It seems like typescript treats importing default exports slightly differently. I actually found a simpler resolution by removing [add-module-exports](https://github.com/danreeves/react-tether/commit/3e6887bc117692fa9b0f7c6d2b3a1ae0e129042e#diff-e56633f72ecc521128b3db6586074d2cR8). @souporserious do you know why this was necessary? It looks like we're having the same typescript issue mentioned [here]( https://github.com/danreeves/react-tether/commit/3e6887bc117692fa9b0f7c6d2b3a1ae0e129042e).

**Comment by souporserious** [comment] 2017-12-06 16:27
I think you should be able to remove `add-module-exports`, I added that a while ago so it wouldn't export things like `ReactTether.default` for the `dist` build. There is probably a better way to do that now though 😇

**Comment by ryprice** [comment] 2018-01-04 02:32
@souporserious I guess you were looking to achieve the opposite of what I am. Would exporting ReactTether.default break things? I've [updated the PR](https://github.com/danreeves/react-tether/pull/53/commits/c93a771d74dabc6a055214717abf1631c84a2b92) anyhow.

**Comment by danreeves** [comment] 2018-02-18 21:15
Hey @ryprice 

I'm not a TypeScript user so could use some input from you.

Is 
```json
{
  "compilerOptions": {
    "module": "es2015",
    "allowSyntheticDefaultImports": true,
  }
}
```
often used? It seems to fix this issue.

I'll probably be accepting your PR and making a major version, since it's a breaking change for CommonJS users.

**Comment by danreeves** [comment] 2018-02-25 20:06
Resolved by https://github.com/danreeves/react-tether/pull/72

**Closed** 2018-02-25 20:06 UTC
